version: '3'
services:
    # Postgres
    postgres:
        image: postgres:12.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=app
        ports:
            - "5555:5432"
    # Flask
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/usr/local/app
        command: >
            /bin/bash -c "
                sleep 5
                python flask_migrations.py
                python load_data.py
                uwsgi --socket 0.0.0.0:5000 \
                      --uid app-server \
                      --enable-threads \
                      --protocol http \
                      --thunder-lock \
                      --processes 4 \
                      --threads 2 \
                      -w wsgi:app \
                      --master
                sleep infinity
            "
        environment:
            - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/app
        depends_on:
            - postgres
        restart: always
        ports:
            - "5000:5000"
